version: '2'
services:
    web:
        build: .
        depends_on:
            - db
    db:
        image: mdillon/postgis:11-alpine
        ports:
            - 5433:5432
        volumes:
            - postgis:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
volumes:
    postgis: {}